// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/all/": {
            "get": {
                "description": "Сокет для получения рейтинга всех участников в контесте (ws://host:port/ws/v1/all?)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WebSocket"
                ],
                "summary": "WebSocket for rating aggregation",
                "parameters": [
                    {
                        "description": "JWT Token",
                        "name": "token",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/balance": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "balance"
                ],
                "summary": "получить баланс",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-model_Balance"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/balance/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "balance"
                ],
                "summary": "получить историю транзакций",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-array_model_Transaction"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/collection": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collection"
                ],
                "summary": "получить все коллекций",
                "parameters": [
                    {
                        "type": "string",
                        "description": "language",
                        "name": "language",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-array_model_Collection"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/contest": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contest"
                ],
                "summary": "получить активные контесты",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "contest_id",
                        "name": "contest_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-array_schema_ContestData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/contest/active": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contest"
                ],
                "summary": "получить активные контесты",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_ContestActivity"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/contest/join": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contest"
                ],
                "summary": "подключиться к розыгрышу",
                "parameters": [
                    {
                        "description": "CreateMark",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.JoinContestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/contest/prize": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contest"
                ],
                "summary": "получить призы контеста",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "contest_id",
                        "name": "contest_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-array_model_ContestPrize"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/contest/read": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contest"
                ],
                "summary": "Прочесть контест книгу",
                "parameters": [
                    {
                        "description": "CreateMark",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.JoinContestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_ContestPassBook"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/hashtag": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hashtag"
                ],
                "summary": "получить все коллекций",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-array_model_Hashtag"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/mark": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mark"
                ],
                "summary": "сохранить в избранное",
                "parameters": [
                    {
                        "description": "CreateMark",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.CreateMark"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-model_Mark"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/mark/:post_id": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mark"
                ],
                "summary": "удалить в избранное",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-array_model_Mark"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/notification": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notification"
                ],
                "summary": "получить уведомления",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-array_model_PushNotification"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/orders": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "список моих заказов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-array_model_Order"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/post": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "post"
                ],
                "summary": "список группированных постов",
                "parameters": [
                    {
                        "type": "string",
                        "description": "hashtag_id",
                        "name": "hashtag_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "collection_id",
                        "name": "collection_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "language",
                        "name": "language",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_PostResponseByGroup"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/post/archive": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "post"
                ],
                "summary": "архивные посты",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-array_schema_ArchivePost"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/post/check-quiz": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "post"
                ],
                "summary": "проверить что квиз прочитан",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "post_id",
                        "name": "post_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-model_UserPost"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/post/filter": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "post"
                ],
                "summary": "список постов с фильтром",
                "parameters": [
                    {
                        "type": "string",
                        "description": "hashtag_id",
                        "name": "hashtag_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "collection_id",
                        "name": "collection_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "language",
                        "name": "language",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "search",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "post_id",
                        "name": "post_ids",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "all, post, partner",
                        "name": "post_type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-array_schema_PostResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/post/read": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "post"
                ],
                "summary": "прочесть книгу",
                "parameters": [
                    {
                        "description": "post",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.ReadPost"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_ReadPostRequest"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/post/save-quiz": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "post"
                ],
                "summary": "сохраниь что квиз прочитан",
                "parameters": [
                    {
                        "description": "post",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.PassQuizPost"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-model_UserPost"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/privacy-terms": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "privacy-terms"
                ],
                "summary": "получить все коллекций",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-array_model_PrivacyTerms"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/product": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "список товаров",
                "parameters": [
                    {
                        "type": "string",
                        "description": "product_tag_id",
                        "name": "product_tag_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-array_model_Product"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/product/buy": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "покупка товара",
                "parameters": [
                    {
                        "description": "post",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.ProductBuyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/recommendation": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collection"
                ],
                "summary": "получить все рекомендаций",
                "parameters": [
                    {
                        "type": "string",
                        "description": "language",
                        "name": "language",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-array_model_Collection"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/referral": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "referral"
                ],
                "summary": "получить реферал код юзера",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-model_ReferralCode"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "referral"
                ],
                "summary": "пометить прочитанным сторис",
                "parameters": [
                    {
                        "type": "string",
                        "description": "referralCode",
                        "name": "referralCode",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-model_ReferralCode"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/referral/available": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "referral"
                ],
                "summary": "получить активность рефералки",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_CheckAvailable"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/stories": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stories"
                ],
                "summary": "получить список сторисов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-array_model_Stories"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stories"
                ],
                "summary": "пометить сторис прочитанным",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "story_page_id",
                        "name": "story_page_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/tags": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "список моих заказов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-array_model_ProductTag"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/user": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "обновить пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/user-device-token": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-device-token"
                ],
                "summary": "получить токен девайса токены пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-array_model_UserDeviceToken"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-device-token"
                ],
                "summary": "сохранить токен девайса токена",
                "parameters": [
                    {
                        "description": "Create device token",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.UserDeviceTokenCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-model_UserDeviceToken"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-device-token"
                ],
                "summary": "удалить токен девайса токены пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "deviceTokenId",
                        "name": "deviceTokenId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/user/:user_id": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "получить пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-model_User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "удалить пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v1/user/mark": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mark"
                ],
                "summary": "все избранное пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "all, post, partner",
                        "name": "filter",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-array_schema_PostResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v2/post": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "post"
                ],
                "summary": "список группированных постов",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "hashtag_id",
                        "name": "hashtag_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "collection_id",
                        "name": "collection_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "language",
                        "name": "language",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_PostResponseByGroup"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        },
        "/api/v2/post/filter": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "post"
                ],
                "summary": "список постов с фильтром",
                "parameters": [
                    {
                        "type": "string",
                        "description": "hashtag_id",
                        "name": "hashtag_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "collection_id",
                        "name": "collection_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "language",
                        "name": "language",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "search",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "post_ids",
                        "name": "post_ids",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "all, post, partner",
                        "name": "post_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-array_schema_PostResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schema.Response-schema_Empty"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Balance": {
            "type": "object",
            "properties": {
                "balance_id": {
                    "type": "integer"
                },
                "coins": {
                    "type": "integer"
                },
                "sapphires": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.Collection": {
            "type": "object",
            "properties": {
                "collection_id": {
                    "type": "integer"
                },
                "image_path": {
                    "type": "string"
                },
                "image_path_kz": {
                    "type": "string"
                },
                "image_path_ru": {
                    "type": "string"
                },
                "is_recommendation": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "name_kz": {
                    "type": "string"
                },
                "name_ru": {
                    "type": "string"
                },
                "posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Post"
                    }
                }
            }
        },
        "model.ContestPrize": {
            "type": "object",
            "properties": {
                "contest_id": {
                    "type": "integer"
                },
                "contest_prize_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "photo_path": {
                    "type": "string"
                },
                "prize_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.Hashtag": {
            "type": "object",
            "properties": {
                "hashtag_id": {
                    "type": "integer"
                },
                "image_path": {
                    "type": "string"
                },
                "is_visible": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "name_kz": {
                    "type": "string"
                },
                "name_ru": {
                    "type": "string"
                },
                "posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Post"
                    }
                }
            }
        },
        "model.Image": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "file_name": {
                    "type": "string"
                },
                "image_id": {
                    "type": "integer"
                },
                "post_id": {
                    "type": "integer"
                },
                "product_id": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "model.Mark": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "mark_id": {
                    "type": "integer"
                },
                "post": {
                    "$ref": "#/definitions/model.Post"
                },
                "post_id": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/model.User"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.Order": {
            "type": "object",
            "properties": {
                "buyer_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "order_id": {
                    "type": "integer"
                },
                "order_products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.OrderProduct"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.OrderProduct": {
            "type": "object",
            "properties": {
                "coins": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "order_id": {
                    "type": "integer"
                },
                "order_product_id": {
                    "type": "integer"
                },
                "product": {
                    "$ref": "#/definitions/model.Product"
                },
                "product_id": {
                    "type": "integer"
                },
                "product_type": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "sapphires": {
                    "type": "integer"
                },
                "sku": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.Post": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "collections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Collection"
                    }
                },
                "company": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "hashtags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Hashtag"
                    }
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Image"
                    }
                },
                "language": {
                    "type": "string"
                },
                "point": {
                    "type": "integer"
                },
                "post_id": {
                    "type": "integer"
                },
                "post_order": {
                    "type": "integer"
                },
                "quiz_time": {
                    "type": "integer"
                },
                "rating_status": {
                    "type": "string"
                },
                "read_time": {
                    "type": "integer"
                },
                "sapphire": {
                    "type": "integer"
                },
                "short_description": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "model.PrivacyTerms": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "privacy_terms_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.Product": {
            "type": "object",
            "properties": {
                "airtable_product_id": {
                    "type": "string"
                },
                "contacts": {
                    "type": "string"
                },
                "contacts_en": {
                    "type": "string"
                },
                "contacts_kz": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "description_en": {
                    "type": "string"
                },
                "description_kz": {
                    "type": "string"
                },
                "discount": {
                    "type": "string"
                },
                "discount_en": {
                    "type": "string"
                },
                "discount_kz": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Image"
                    }
                },
                "offer": {
                    "type": "string"
                },
                "offer_en": {
                    "type": "string"
                },
                "offer_kz": {
                    "type": "string"
                },
                "point": {
                    "type": "integer"
                },
                "product_id": {
                    "type": "integer"
                },
                "product_tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ProductTag"
                    }
                },
                "product_type": {
                    "type": "string"
                },
                "sapphire": {
                    "type": "integer"
                },
                "sell_type": {
                    "type": "string"
                },
                "sku": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "title_en": {
                    "type": "string"
                },
                "title_kz": {
                    "type": "string"
                }
            }
        },
        "model.ProductTag": {
            "type": "object",
            "properties": {
                "image_path": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "name_kz": {
                    "type": "string"
                },
                "name_ru": {
                    "type": "string"
                },
                "product_tag_id": {
                    "type": "integer"
                }
            }
        },
        "model.Profile": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "model.PushNotification": {
            "type": "object",
            "properties": {
                "condition": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "is_sended": {
                    "type": "boolean"
                },
                "push_notification_id": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "topic": {
                    "type": "string"
                }
            }
        },
        "model.ReferralCode": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "referral_code": {
                    "type": "string"
                },
                "referral_code_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.Stories": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "icon_path": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "stories_id": {
                    "type": "integer"
                },
                "story_pages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.StoryPage"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.StoryPage": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "image_path": {
                    "type": "string"
                },
                "is_readed": {
                    "type": "boolean"
                },
                "page_order": {
                    "type": "integer"
                },
                "stories_id": {
                    "type": "integer"
                },
                "story_page_id": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "model.Transaction": {
            "type": "object",
            "properties": {
                "coins": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "outer_id": {
                    "type": "integer"
                },
                "reason": {
                    "type": "string"
                },
                "sapphires": {
                    "type": "integer"
                },
                "transaction_id": {
                    "type": "integer"
                },
                "transaction_type": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "confirmation_send_at": {
                    "type": "string"
                },
                "confirmation_token": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "email_confirmed_at": {
                    "type": "string"
                },
                "encrypted_password": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "profile": {
                    "$ref": "#/definitions/model.Profile"
                }
            }
        },
        "model.UserDeviceToken": {
            "type": "object",
            "properties": {
                "device_token": {
                    "type": "string"
                },
                "user_device_token_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.UserPost": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "post_id": {
                    "type": "integer"
                },
                "quiz_points": {
                    "type": "integer"
                },
                "quiz_sapphires": {
                    "type": "integer"
                },
                "read_end": {
                    "type": "boolean"
                },
                "user_id": {
                    "type": "string"
                },
                "user_post_id": {
                    "type": "integer"
                }
            }
        },
        "schema.ArchivePost": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "collections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Collection"
                    }
                },
                "company": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "earned_coins": {
                    "type": "integer"
                },
                "earned_sapphires": {
                    "type": "integer"
                },
                "hashtags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Hashtag"
                    }
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Image"
                    }
                },
                "language": {
                    "type": "string"
                },
                "point": {
                    "type": "integer"
                },
                "post_id": {
                    "type": "integer"
                },
                "post_order": {
                    "type": "integer"
                },
                "quiz_passed": {
                    "type": "boolean"
                },
                "quiz_time": {
                    "type": "integer"
                },
                "rating_status": {
                    "type": "string"
                },
                "read_time": {
                    "type": "integer"
                },
                "sapphire": {
                    "type": "integer"
                },
                "short_description": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "schema.CheckAvailable": {
            "type": "object",
            "properties": {
                "already_used_referral_code": {
                    "type": "boolean"
                }
            }
        },
        "schema.ContestActivity": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.ContestData"
                    }
                },
                "ended": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.ContestResultPrize"
                    }
                }
            }
        },
        "schema.ContestData": {
            "type": "object",
            "properties": {
                "already_joined": {
                    "type": "boolean"
                },
                "contest_id": {
                    "type": "integer"
                },
                "current_day_number": {
                    "type": "integer"
                },
                "end_time": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "total_users_count": {
                    "type": "integer"
                }
            }
        },
        "schema.ContestPassBook": {
            "type": "object",
            "properties": {
                "coins": {
                    "type": "integer"
                },
                "points": {
                    "type": "integer"
                }
            }
        },
        "schema.ContestResultPrize": {
            "type": "object",
            "properties": {
                "consolation_prize_sapphire": {
                    "type": "integer"
                },
                "contest_id": {
                    "type": "integer"
                },
                "number": {
                    "type": "integer"
                },
                "prize": {
                    "$ref": "#/definitions/model.ContestPrize"
                }
            }
        },
        "schema.CreateMark": {
            "type": "object",
            "properties": {
                "post_id": {
                    "type": "integer"
                }
            }
        },
        "schema.Empty": {
            "type": "object"
        },
        "schema.JoinContestRequest": {
            "type": "object",
            "properties": {
                "contest_id": {
                    "type": "integer"
                }
            }
        },
        "schema.PassQuizPost": {
            "type": "object",
            "properties": {
                "post_id": {
                    "type": "integer"
                },
                "quiz_points": {
                    "type": "integer"
                },
                "quiz_sapphires": {
                    "type": "integer"
                }
            }
        },
        "schema.PostResponse": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "collections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Collection"
                    }
                },
                "company": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "hashtags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Hashtag"
                    }
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Image"
                    }
                },
                "is_already_read": {
                    "type": "boolean"
                },
                "is_marked": {
                    "type": "boolean"
                },
                "language": {
                    "type": "string"
                },
                "mark_id": {
                    "type": "integer"
                },
                "point": {
                    "type": "integer"
                },
                "post_id": {
                    "type": "integer"
                },
                "post_order": {
                    "type": "integer"
                },
                "post_type": {
                    "type": "string"
                },
                "quiz_passed": {
                    "type": "boolean"
                },
                "quiz_time": {
                    "type": "integer"
                },
                "rating_status": {
                    "type": "string"
                },
                "read_time": {
                    "type": "integer"
                },
                "sapphire": {
                    "type": "integer"
                },
                "short_description": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "schema.PostResponseByGroup": {
            "type": "object",
            "properties": {
                "bestsellers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.PostResponse"
                    }
                },
                "continue_reading": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.PostResponse"
                    }
                },
                "partners": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.PostResponse"
                    }
                }
            }
        },
        "schema.ProductBuyRequest": {
            "type": "object",
            "properties": {
                "product_id": {
                    "type": "integer"
                }
            }
        },
        "schema.ReadPost": {
            "type": "object",
            "properties": {
                "end": {
                    "type": "boolean"
                },
                "post_id": {
                    "type": "integer"
                }
            }
        },
        "schema.ReadPostRequest": {
            "type": "object",
            "properties": {
                "end_reading": {
                    "type": "boolean"
                },
                "post_id": {
                    "type": "integer"
                }
            }
        },
        "schema.Response-array_model_Collection": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Collection"
                    }
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-array_model_ContestPrize": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ContestPrize"
                    }
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-array_model_Hashtag": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Hashtag"
                    }
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-array_model_Mark": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Mark"
                    }
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-array_model_Order": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Order"
                    }
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-array_model_PrivacyTerms": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.PrivacyTerms"
                    }
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-array_model_Product": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Product"
                    }
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-array_model_ProductTag": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ProductTag"
                    }
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-array_model_PushNotification": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.PushNotification"
                    }
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-array_model_Stories": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Stories"
                    }
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-array_model_Transaction": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Transaction"
                    }
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-array_model_UserDeviceToken": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.UserDeviceToken"
                    }
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-array_schema_ArchivePost": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.ArchivePost"
                    }
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-array_schema_ContestData": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.ContestData"
                    }
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-array_schema_PostResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.PostResponse"
                    }
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-model_Balance": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/model.Balance"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-model_Mark": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/model.Mark"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-model_ReferralCode": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/model.ReferralCode"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-model_User": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/model.User"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-model_UserDeviceToken": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/model.UserDeviceToken"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-model_UserPost": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/model.UserPost"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-schema_CheckAvailable": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/schema.CheckAvailable"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-schema_ContestActivity": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/schema.ContestActivity"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-schema_ContestPassBook": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/schema.ContestPassBook"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-schema_Empty": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/schema.Empty"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-schema_PostResponseByGroup": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/schema.PostResponseByGroup"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Response-schema_ReadPostRequest": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/schema.ReadPostRequest"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.UserDeviceTokenCreateRequest": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "swagger API",
	Description:      "Это пример сервера с использованием Swagger в Gin.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
